---
- name: k8s Setting
  hosts: all
  gather_facts: no
  tasks:
    - name: add hosts
      lineinfile:
        path: /etc/hosts
        insertafter: 'localhost6.localdomain6'
        line: |
          192.168.0.136 k8s-master
          192.168.0.137 k8s-node1
          192.168.0.138 k8s-node2
          
    - name: stop firewalld
      shell: |
        systemctl stop firewalld
        systemctl disable firewalld
        
    - name: disable selinux
      shell: setenforce 0
      
    - name: disable selinux
      replace:
        path: /etc/sysconfig/selinux
        regexp: "SELINUX=enforcing"
        replace: "SELINUX=disabled"
        
    - name: enable br_netfilter
      shell: |
        modprobe br_netfilter
        echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
        modprobe br_netfilter
        
    - name: swappiness
      shell: |
        swapoff -a
        
    - name: set swap
      replace:
        path: /etc/fstab
        regexp: "/dev/mapper/centos-swap swap"
        replace: "#/dev/mapper/centos-swap swap"
        
    - name: set swap2
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward = 1
        
    - name: install docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
        
    - name: install docker2
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 
      
    - name: install docker3
      yum: name=docker-ce state=present
      
    - name: docker restart and set enable
      shell: systemctl enable docker && systemctl start docker
      
    - name: make k8s.conf
      file:
        path: /etc/sysctl.d/k8s.conf
        state: touch
        owner: root
        group: root
        mode: 0644
      
    - name: k8s.conf
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          
    - name: make kubernetes.repo
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch
        owner: root
        group: root
        mode: 0644
        
    - name: k8s.conf
      lineinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        line: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=0
          repo_gpgcheck=0
          gpgkey=https://${gg_pkg}/yum-key.gpg https://${gg_pkg}/rpm-package-key.gpg
          
    - name: install k8s
      yum:
        name:
          - kubectl-1.18.4
          - kubelet-1.18.4
          - kubeadm-1.18.4
        state: present
        
    - name: enable kubelet
      shell: systemctl enable kubelet && systemctl start kubelet
    
    - name: make daemon.json
      file:
        path: /etc/docker/daemon.json
        state: touch
        owner: root
        group: root
        mode: 644
        
    - name: daemon.json
      lineinfile:
        path: /etc/docker/daemon.json
        line: |
          {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
          "max-size": "100m"
          },
          "storage-driver": "overlay2"
          }
