---
- name: RabbitMQ setting
  hosts: all
  gather_facts: no
  become: True
  tasks:
    - name: add hosts
      lineinfile:
        path: /etc/hosts
        insertafter: 'localhost6.localdomain6'
        line: |
          192.168.0.11 vr-001
          192.168.0.12 vr-002
          192.168.0.13 vr-003
          
    - name: disable selinux
      shell: setenforce 0
      
    - name: disable selinux
      replace:
        path: /etc/sysconfig/selinux
        regexp: "SELINUX=enforcing"
        replace: "SELINUX=disabled"
        
    - name: swappiness
      shell: swapoff -a
        
    - name: set swap
      replace:
        path: /etc/fstab
        regexp: "/dev/mapper/centos-swap swap"
        replace: "#/dev/mapper/centos-swap swap"
        
    - name: set swap2
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward = 1
        
    - name: yum update
      yum: name='*' state=latest
      
    - name: install epel-release, net-tools
      yum:
        name:
          - epel-release
          - net-tools
        state: latest
        
    - name: install erlang from remote repo
      yum:
        name: https://github.com/rabbitmq/erlang-rpm/releases/download/v22.1.3/erlang-22.1.3-1.el7.x86_64.rpm
        state: present
        
    - name: install rabbitmq from remote repo
      yum:
        name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.0-rc.1/rabbitmq-server-3.8.0.rc.1-1.el7.noarch.rpm
        state: present
       
    - name: start rabbitmq
      shell: systemctl start rabbitmq-server
      
    - name: enable rabbitmq
      shell: systemctl enable rabbitmq-server
      
    - name: plugins enable
      shell: rabbitmq-plugins enable rabbitmq_management
      
    - name: restart rabbitmq
      shell: systemctl restart rabbitmq-server
        
    - name: open port for rabbitmq
      shell: |
        firewall-cmd --permanent --add-port=4369/tcp
        firewall-cmd --permanent --add-port=5672/tcp
        firewall-cmd --permanent --add-port=15672/udp
        firewall-cmd --permanent --add-port=15674/udp
        firewall-cmd --permanent --add-port=25672/udp
        firewall-cmd --reload

- name: get master erlang.cookie
  hosts: master
  gather_facts: no
  become: True
  tasks:    
    - name: check file exists
      stat:
        path: /var/lib/rabbitmq/.erlang.cookie
      register: file_check
      
    - name: get master erlang.cookie
      fetch:
        src: "/var/lib/rabbitmq/.erlang.cookie"
        dest: "/home/rabbitmq/.erlang.cookie"
        flat: yes
      when: file_check.stat.exists
  
- name: send master's cookie
  hosts: nodes
  gather_facts: no
  become: True
  tasks:     
    - name: send master's cookie
      copy:
        src: "/home/rabbitmq/.erlang.cookie"
        dest: "/var/lib/rabbitmq/"
        
    - name: clustering
      shell: |
        systemctl restart rabbitmq-server
        rabbitmqctl stop_app
        rabbitmqctl reset
        rabbitmqctl join_cluster rabbit@vr-001
        rabbitmqctl start_app
        
