---
- name: server basic setting
  hosts: DB
  gather_facts: no
  tasks:
    - name: uninstall mysql-server
      yum:
        name:
          - mysql-server
          - mysql
          - mysql-devel
        state: absent
        
    - name: delete directory
      file:
        path: /var/lib/mysql/
        state: absent

    - name: make MariaDB.repo
      file:
        path: /etc/yum.repos.d/MariaDB.repo
        state: touch
        owner: root
        group: root
        mode: 0644
        
    - name: update MariaDB.repo
      lineinfile:
        path: /etc/yum.repos.d/MariaDB.repo
        line: |
          [mariadb]
          name = MariaDB
          baseurl = http://yum.mariadb.org/10.0/centos7-amd64
          gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
          gpgcheck=1
          
    - name: install socat MariaDB Galera-cluster
      yum:
        name:
          - socat
          - MariaDB-Galera-server
          - MariaDB-client
          - rsync
          - galera
        state: latest
