---
- name: server basic setting
  hosts: all
  gather_facts: no
  tasks:
    - name: selinux
      replace:
        path: /etc/sysconfig/selinux
        regexp: "SELINUX=enforcing"
        replace: "SELINUX=disabled"
        
    - name: yum update
      yum: name='*' state=latest
      
    - name: install epel-release
      yum: name=epel-release state=present
      
    - name: install net-tools
      yum: name=net-tools state=present
      
    - name: add hosts
      lineinfile:
        path: /etc/hosts
        insertafter: 'localhost6.localdomain6'
        line: |
          192.168.100.75 Web
          192.168.100.73 Was1
          192.168.100.88 DB1
      
- name: Web Server Setting
  hosts: Web
  gather_facts: no
  tasks:
    - name: install nginx haproxy
      yum:
        name:
          - nginx
          - haproxy
        state: latest
        
    - name: add port
      shell: |
        firewall-cmd --permanent --add-port=443/tcp
        firewall-cmd --permanent --add-port=15672/tcp
        firewall-cmd --permanent --add-port=15670/tcp
        firewall-cmd --permanent --add-port=5670/tcp
        
    - name: reload
      shell: firewall-cmd --reload
      
    - name: copy nginx file
      copy:
        src: "/home/{{ item }}"
        dest: /etc/nginx/
      with_items:
        - nginx.conf
        - service.vegas-solution.com
        
    - name: make directory
      shell: mkdir /etc/nginx/ssl
      
    - name: copy directory
      unarchive:
        src: /home/ssl.tar
        dest: /etc/nginx/ssl
        
    - name: copy haproxy file
      copy:
       src: /home/haproxy.cfg
       dest: /etc/haproxy/
       
    - name: nginx start
      service: name=nginx state=started
      
    - name: haproxy start
      service: name=haproxy state=started
